[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pond"
version = "0.1.0"
description = "Pond Python package"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Jeremy" }
]
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["pond*"]